name: emoji

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ secrets.GITHUB_USERNAME }}"
          git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
          echo "machine github.com login ${{ secrets.GITHUB_USERNAME }} password ${{ secrets.GITHUB_TOKEN }}" > ~/.netrc
          npx gh-pages -d build