name: emoji
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    env:
      CI: true
  
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest

    steps:
      - run: npm install
      - run: npm test