name: Configure Git and Create .netrc

on: [push]

jobs:
  configure-git:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name "sai1781"
          git config --global user.email "nagasaitac143@gmail.com"

      - name: Create .netrc
        run: |
          echo "machine github.com login sai1781 password $GITHUB_TOKEN" > ~/.netrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub provides GITHUB_TOKEN by default

      - name: Verify .netrc
        run: cat ~/.netrc
